# Copyright 2017, Zededa Inc.
# Written by Cherry G. Mathew <cherry@zededa.com>

FROM ${SDK_REPO_BASE}:${ALPINE_MULTIARCH_VER} AS sdk-base

# Prep software
RUN apk update
RUN apk add ${ALPINE_SDK_BASE_PKGS}
FROM scratch
ENTRYPOINT []
CMD []
WORKDIR /

COPY --from=sdk-base / /

# Prep user
RUN adduser -D ${ALPINE_SDK_USER}

