# Copyright 2017, Zededa Inc.
# Written by Cherry G. Mathew <cherry@zededa.com>

# XXX: TODO: For cross ARCH build - install the static binary, if needed
# FROM multiarch/qemu-user-static:register AS qemu-static

FROM ${SDK_REPO_BASE}:${ALPINE_MULTIARCH_VER} AS sdk-base


# Prep software
RUN apk update
RUN apk add ${ALPINE_SDK_PKGS}

FROM sdk-base AS go-base
RUN  go get -v -u github.com/linuxkit/linuxkit/src/cmd/linuxkit

FROM scratch
ENTRYPOINT []
CMD []
WORKDIR /

COPY --from=sdk-base / /
COPY --from=go-base /root/go/pkg /usr/lib/go/
COPY --from=go-base /root/go/src /usr/lib/go/
COPY --from=go-base /root/go/bin/ /usr/local/bin/

# Prep user
RUN adduser -D ${ALPINE_SDK_USER} -u ${ALPINE_SDK_USERID}
RUN groupmod -g ${DOCKER_GID} docker
RUN adduser ${ALPINE_SDK_USER} docker
